//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace businessProBms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public int purchaseId { get; set; }
        public System.DateTime purchaseDate { get; set; }
        public int vendorCode { get; set; }
        public string vendorName { get; set; }
        public int purVoucherNo { get; set; }
    
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
    }
}
