//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace businessProBms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.SaleDetails = new HashSet<SaleDetail>();
        }
    
        public int saleId { get; set; }
        public System.DateTime saleDate { get; set; }
        public int customerCode { get; set; }
        public string customerName { get; set; }
        public int saleVoucherNo { get; set; }
    
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
    }
}
