//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace businessProBms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public Voucher()
        {
            this.VoucherBodies = new HashSet<VoucherBody>();
        }
    
        public int voucherNo { get; set; }
        public System.DateTime voucherDate { get; set; }
        public Nullable<int> voucherType { get; set; }
    
        public virtual ICollection<VoucherBody> VoucherBodies { get; set; }
    }
}
